# Generated by Django 4.2.2 on 2023-07-09 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KBItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URI', models.CharField(max_length=500)),
                ('userTags', models.CharField()),
                ('itemContent', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ImageKBItem',
            fields=[
                ('kbitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbItems.kbitem')),
            ],
            bases=('kbItems.kbitem',),
        ),
        migrations.CreateModel(
            name='TextKBItem',
            fields=[
                ('kbitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kbItems.kbitem')),
            ],
            bases=('kbItems.kbitem',),
        ),
    ]
