# Generated by Django 4.2.2 on 2023-10-02 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kbItems", "0002_kbitem_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="kbitem",
            name="sourceName",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="kbitem",
            name="title",
            field=models.TextField(default=""),
        ),
    ]
